DELETE FROM events
WHERE title IN (
  'Neon Pulse Lima 2026',
  'Cumbre Tech Andina 2026',
  'Clasico de Leyendas',
  'Festival Sabores de Barrio',
  'Noche de Stand Up Central',
  'Expo Arte Inmersivo',
  'Maraton Urbana 10K',
  'Campus Product Design Live',
  'Sunset Rooftop Sessions',
  'Foro Futuro IA y Negocios'
);

WITH organizer AS (
  SELECT id
  FROM users
  WHERE email = 'organizer@crowdpass.com'
),
event_rows AS (
  INSERT INTO events (
    organizer_id,
    category_id,
    title,
    description,
    additional_info,
    featured_image_url,
    promo_video_url,
    venue,
    event_date,
    starts_at,
    ends_at,
    visibility,
    age_restriction,
    country,
    city,
    address_line,
    address_reference,
    meeting_point,
    latitude,
    longitude,
    total_tickets,
    available_tickets,
    price,
    status,
    published_at
  )
  VALUES
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'concerts'),
      'Neon Pulse Lima 2026',
      'Festival nocturno de musica electronica con dos escenarios, luces inmersivas y food court premium.',
      'Ingreso digital, zona cashless y activaciones con marcas tecnologicas.',
      'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
      'https://www.youtube.com/watch?v=ScMzIvxBSi4',
      'Arena Costa 360',
      NOW() + INTERVAL '10 days',
      NOW() + INTERVAL '10 days',
      NOW() + INTERVAL '10 days 7 hours',
      'public',
      '18_plus',
      'Peru',
      'Lima',
      'Av. Del Pacifico 450, Costa Verde',
      'Frente al acceso sur del recinto',
      'Puerta 3',
      -12.1202000,
      -77.0438000,
      1200,
      1200,
      149.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'technology'),
      'Cumbre Tech Andina 2026',
      'Encuentro regional sobre software, cloud, producto digital y escalabilidad para equipos de tecnologia.',
      'Incluye networking, coffee breaks y certificacion digital.',
      'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg',
      'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      'Centro de Convenciones Andinas',
      NOW() + INTERVAL '14 days',
      NOW() + INTERVAL '14 days 9 hours',
      NOW() + INTERVAL '14 days 18 hours',
      'public',
      'all_audiences',
      'Peru',
      'Lima',
      'Jr. Innovacion 210, San Isidro',
      'Costado del estacionamiento principal',
      'Lobby principal',
      -12.0972000,
      -77.0365000,
      500,
      500,
      95.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'sports'),
      'Clasico de Leyendas',
      'Partido exhibicion con exjugadores historicos y experiencia fan zone antes del encuentro.',
      'Aforo sectorizado con ingreso por QR y activaciones familiares.',
      'https://images.pexels.com/photos/274422/pexels-photo-274422.jpeg',
      'https://www.youtube.com/watch?v=ysz5S6PUM-U',
      'Estadio Metropolitano',
      NOW() + INTERVAL '18 days',
      NOW() + INTERVAL '18 days 16 hours',
      NOW() + INTERVAL '18 days 19 hours',
      'public',
      'all_audiences',
      'Peru',
      'Arequipa',
      'Av. Deporte 900, Cerro Colorado',
      'Ingreso por tribuna norte',
      'Puerta A',
      -16.4040000,
      -71.5596000,
      2000,
      2000,
      80.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'gastronomy'),
      'Festival Sabores de Barrio',
      'Experiencia gastronomica con chefs invitados, mercado local y musica en vivo todo el dia.',
      'Acceso por bloques horarios para mejorar la experiencia del publico.',
      'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
      'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
      'Parque Gastronomico Central',
      NOW() + INTERVAL '6 days',
      NOW() + INTERVAL '6 days 11 hours',
      NOW() + INTERVAL '6 days 21 hours',
      'public',
      'all_audiences',
      'Peru',
      'Cusco',
      'Av. Cultura 1200',
      'A media cuadra del acceso principal',
      'Modulo de acreditacion',
      -13.5319000,
      -71.9675000,
      900,
      900,
      35.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'theater'),
      'Noche de Stand Up Central',
      'Show de comedia con lineup nacional, open mic previo y experiencia lounge.',
      'Evento numerado con opcion premium y meet & greet.',
      'https://images.pexels.com/photos/713149/pexels-photo-713149.jpeg',
      'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
      'Teatro Punto Vivo',
      NOW() + INTERVAL '8 days',
      NOW() + INTERVAL '8 days 20 hours',
      NOW() + INTERVAL '8 days 22 hours',
      'public',
      '18_plus',
      'Peru',
      'Lima',
      'Calle Escena 180, Miraflores',
      'Puerta frente al parque',
      'Hall del teatro',
      -12.1229000,
      -77.0297000,
      320,
      320,
      55.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'art'),
      'Expo Arte Inmersivo',
      'Recorrido de arte digital con mapping, instalaciones interactivas y experiencias sensoriales.',
      'Ideal para publico general, parejas y creadores visuales.',
      'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
      'https://www.youtube.com/watch?v=ScMzIvxBSi4',
      'Galeria Prisma',
      NOW() + INTERVAL '12 days',
      NOW() + INTERVAL '12 days 10 hours',
      NOW() + INTERVAL '12 days 20 hours',
      'public',
      'all_audiences',
      'Peru',
      'Lima',
      'Av. Arte 560, Barranco',
      'Ingreso lateral por patio cultural',
      'Recepcion principal',
      -12.1475000,
      -77.0202000,
      600,
      600,
      42.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'sports'),
      'Maraton Urbana 10K',
      'Carrera certificada con kit oficial, tracking por chip y zona de recuperacion post meta.',
      'Categorias open y master con kit de corredor incluido.',
      'https://images.pexels.com/photos/2402777/pexels-photo-2402777.jpeg',
      'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      'Circuito Malecon Norte',
      NOW() + INTERVAL '20 days',
      NOW() + INTERVAL '20 days 6 hours',
      NOW() + INTERVAL '20 days 11 hours',
      'public',
      'all_audiences',
      'Peru',
      'Trujillo',
      'Malecon Norte km 2',
      'Salida frente al arco principal',
      'Zona de check-in',
      -8.1118000,
      -79.0288000,
      1500,
      1500,
      65.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'technology'),
      'Campus Product Design Live',
      'Jornada intensiva de UX, research y diseño de interfaces con workshops practicos.',
      'Incluye material de trabajo y acceso a grabaciones.',
      'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg',
      'https://www.youtube.com/watch?v=ysz5S6PUM-U',
      'Hub Creativo Norte',
      NOW() + INTERVAL '16 days',
      NOW() + INTERVAL '16 days 9 hours',
      NOW() + INTERVAL '16 days 17 hours',
      'public',
      'all_audiences',
      'Peru',
      'Lima',
      'Av. Creatividad 78, Jesus Maria',
      'Ingreso por patio central',
      'Modulo de registro',
      -12.0740000,
      -77.0506000,
      420,
      420,
      110.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'concerts'),
      'Sunset Rooftop Sessions',
      'Sesion musical al atardecer con DJs locales, cocteleria de autor y vista panoramica.',
      'Experiencia pensada para aforo limitado y consumo en lounge.',
      'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
      'https://www.youtube.com/watch?v=ScMzIvxBSi4',
      'Rooftop Aurora',
      NOW() + INTERVAL '5 days',
      NOW() + INTERVAL '5 days 17 hours',
      NOW() + INTERVAL '5 days 23 hours',
      'public',
      '18_plus',
      'Peru',
      'Lima',
      'Av. Horizonte 450, San Borja',
      'Ascensor panoramico torre B',
      'Recepcion del rooftop',
      -12.0892000,
      -76.9997000,
      180,
      180,
      70.00,
      'published',
      NOW()
    ),
    (
      (SELECT id FROM organizer),
      (SELECT id FROM event_categories WHERE slug = 'conferences'),
      'Foro Futuro IA y Negocios',
      'Conferencia ejecutiva con casos de uso reales de inteligencia artificial aplicada a negocio.',
      'Paneles con founders, CTOs y lideres de transformacion digital.',
      'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg',
      'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      'Auditorio Vertex',
      NOW() + INTERVAL '22 days',
      NOW() + INTERVAL '22 days 8 hours',
      NOW() + INTERVAL '22 days 15 hours',
      'public',
      'all_audiences',
      'Peru',
      'Lima',
      'Av. Empresarial 250, La Molina',
      'Ingreso por torre corporativa',
      'Lobby principal',
      -12.0826000,
      -76.9452000,
      700,
      700,
      120.00,
      'published',
      NOW()
    )
  RETURNING id, title
)
INSERT INTO event_ticket_types (
  event_id,
  name,
  currency,
  price,
  stock_total,
  stock_available,
  sales_starts_at,
  sales_ends_at,
  sales_end_mode,
  max_per_order,
  max_per_user
)
SELECT
  e.id,
  t.name,
  'PEN',
  t.price,
  t.stock_total,
  t.stock_available,
  NOW(),
  NOW() + INTERVAL '25 days',
  'until_event_start',
  t.max_per_order,
  t.max_per_user
FROM event_rows e
JOIN (
  VALUES
    ('Neon Pulse Lima 2026', 'General', 149.00, 900, 900, 4, 6),
    ('Neon Pulse Lima 2026', 'VIP', 289.00, 300, 300, 2, 4),
    ('Cumbre Tech Andina 2026', 'General', 95.00, 350, 350, 3, 5),
    ('Cumbre Tech Andina 2026', 'Full Experience', 180.00, 150, 150, 2, 3),
    ('Clasico de Leyendas', 'Tribuna General', 80.00, 1400, 1400, 6, 8),
    ('Clasico de Leyendas', 'Occidente', 150.00, 600, 600, 4, 6),
    ('Festival Sabores de Barrio', 'Ingreso General', 35.00, 750, 750, 5, 8),
    ('Festival Sabores de Barrio', 'Pase Degustacion', 75.00, 150, 150, 2, 4),
    ('Noche de Stand Up Central', 'General', 55.00, 240, 240, 4, 6),
    ('Noche de Stand Up Central', 'Meet & Greet', 110.00, 80, 80, 2, 2),
    ('Expo Arte Inmersivo', 'Entrada Libre', 42.00, 500, 500, 4, 6),
    ('Expo Arte Inmersivo', 'Acceso Premium', 68.00, 100, 100, 2, 4),
    ('Maraton Urbana 10K', 'Kit Runner', 65.00, 1300, 1300, 3, 4),
    ('Maraton Urbana 10K', 'Kit Elite', 110.00, 200, 200, 1, 2),
    ('Campus Product Design Live', 'Workshop Pass', 110.00, 280, 280, 2, 3),
    ('Campus Product Design Live', 'Mentoring Pass', 210.00, 140, 140, 1, 2),
    ('Sunset Rooftop Sessions', 'General', 70.00, 130, 130, 3, 4),
    ('Sunset Rooftop Sessions', 'Lounge', 135.00, 50, 50, 2, 3),
    ('Foro Futuro IA y Negocios', 'Pase Ejecutivo', 120.00, 520, 520, 3, 4),
    ('Foro Futuro IA y Negocios', 'Networking Pro', 220.00, 180, 180, 2, 3)
) AS t(title, name, price, stock_total, stock_available, max_per_order, max_per_user)
  ON t.title = e.title;
